volumes:
  baseapp:
services:
  better-auth-sample:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - baseapp:/tmp/baseapp
    ports:
      - 127.0.0.1:3000:3000